### ISSUE TITLE
Kanban board

### ISSUE THREAD

**Issue by abrormukimov** [abrormukimov/js-capstone#21]
https://github.com/abrormukimov/js-capstone/projects/4

There are 3 contributors in this group capstone project

**Comment by dasileker** [comment]
### **Hi @abrormukimov** , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that you have the wrong link on your issue page, please add the repo/project

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

**Comment by abrormukimov** [comment]
Did you mean this link: https://github.com/abrormukimov/js-capstone

This is the link to our repository? What do you mean by 'add the repo/project'? We would be glad to know what exactly we have to add

**Comment by omar-labana** [comment]
Hi  team, 

Your project is complete!  There is nothing else to say other than... it's time to start it ☆*: .｡. o(≧▽≦)o .｡.:*☆
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
